# Generated by Django 6.0 on 2025-12-21 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ชื่อ-นามสกุล')),
                ('position', models.CharField(max_length=100, verbose_name='ตำแหน่ง')),
                ('base_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='เงินประจำตำแหน่ง')),
                ('level_weight', models.DecimalField(decimal_places=2, default=1.0, max_digits=4, verbose_name='ตัวคูณโบนัส')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='employees.employee', verbose_name='หัวหน้างาน')),
            ],
        ),
    ]
