# Generated by Django 6.0 on 2025-12-22 15:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='manager',
        ),
        migrations.AddField(
            model_name='employee',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='วันเกิด'),
        ),
        migrations.AddField(
            model_name='employee',
            name='bonus_amount',
            field=models.CharField(default='0.00', max_length=50),
        ),
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='แผนก'),
        ),
        migrations.AddField(
            model_name='employee',
            name='emp_id',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='รหัสพนักงาน'),
        ),
        migrations.AddField(
            model_name='employee',
            name='hire_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='วันที่เริ่มงาน'),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='สถานะทำงานอยู่'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='base_allowance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='เงินเดือน'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='level_weight',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5, verbose_name='ตัวคูณโบนัส'),
        ),
    ]
