# Generated by Django 6.0 on 2025-12-22 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_remove_employee_manager_employee_birth_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_policy_accepted',
            field=models.BooleanField(default=False, verbose_name='✅ เซ็นรับทราบกฎระเบียบแล้ว'),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_resigned',
            field=models.BooleanField(default=False, verbose_name='❌ ลาออกแล้ว (Resigned)'),
        ),
        migrations.AddField(
            model_name='employee',
            name='resume_link',
            field=models.URLField(blank=True, null=True, verbose_name='ลิงก์ใบสมัคร/CV'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='✅ สถานะทำงานอยู่ (Active)'),
        ),
    ]
