# Generated by Django 6.0 on 2025-12-22 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_employee_is_policy_accepted_employee_is_resigned_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='is_policy_accepted',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='is_resigned',
        ),
        migrations.AddField(
            model_name='employee',
            name='policy_doc_link',
            field=models.URLField(blank=True, null=True, verbose_name='🔗 ลิงก์ลายเซ็นรับทราบกฎระเบียบ'),
        ),
        migrations.AddField(
            model_name='employee',
            name='resignation_doc_link',
            field=models.URLField(blank=True, null=True, verbose_name='🔗 ลิงก์ใบลาออก (ถ้ามี)'),
        ),
        migrations.AddField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('ACTIVE', '✅ ทำงานอยู่ (Active)'), ('RESIGNED', '❌ ลาออกแล้ว (Resigned)')], default='ACTIVE', max_length=10, verbose_name='สถานะการทำงาน'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='resume_link',
            field=models.URLField(blank=True, null=True, verbose_name='🔗 ลิงก์ใบสมัคร/CV'),
        ),
    ]
