# Generated by Django 6.0 on 2025-12-22 16:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_remove_employee_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='วันที่')),
                ('time_in', models.TimeField(blank=True, null=True, verbose_name='เวลาเข้างาน')),
                ('time_out', models.TimeField(blank=True, null=True, verbose_name='เวลาออกงาน')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee', verbose_name='ชื่อพนักงาน')),
            ],
        ),
    ]
