# Generated by Django 6.0 on 2025-12-22 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('SICK', '🤒 ลาป่วย (Sick Leave)'), ('VACATION', '🏖️ ลาพักร้อน (Vacation)'), ('BUSINESS', '💼 ลากิจ (Business Leave)')], default='SICK', max_length=10, verbose_name='ประเภทการลา')),
                ('start_date', models.DateField(verbose_name='ลาตั้งแต่วันที่')),
                ('end_date', models.DateField(verbose_name='ถึงวันที่')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='เหตุผล')),
                ('status', models.CharField(choices=[('PENDING', '🟡 รออนุมัติ'), ('APPROVED', '🟢 อนุมัติแล้ว'), ('REJECTED', '🔴 ไม่อนุมัติ')], default='PENDING', max_length=10, verbose_name='สถานะ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่ยื่นใบลา')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee', verbose_name='ชื่อพนักงาน')),
            ],
        ),
    ]
