# Generated by Django 5.1.3 on 2025-12-24 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0007_employee_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="birth_date",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="emp_id",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="hire_date",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="policy_doc_link",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="resignation_doc_link",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="resume_link",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="user",
        ),
        migrations.RemoveField(
            model_name="leaverequest",
            name="created_at",
        ),
        migrations.AddField(
            model_name="employee",
            name="employee_id",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                unique=True,
                verbose_name="รหัสพนักงาน",
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="employees.employee"
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="time_in",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="time_out",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="base_allowance",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="employee",
            name="department",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="level_weight",
            field=models.FloatField(
                choices=[
                    (1.0, "Staff (x1)"),
                    (1.5, "Manager (x1.5)"),
                    (2.0, "Exec (x2)"),
                ],
                default=1.0,
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="employee",
            name="position",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="employee",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "ทำงานอยู่"),
                    ("PROBATION", "ทดลองงาน"),
                    ("RESIGNED", "ลาออก"),
                ],
                default="ACTIVE",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="leaverequest",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="employees.employee"
            ),
        ),
        migrations.AlterField(
            model_name="leaverequest",
            name="end_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="leaverequest",
            name="leave_type",
            field=models.CharField(
                choices=[
                    ("SICK", "ลาป่วย"),
                    ("BUSINESS", "ลากิจ"),
                    ("VACATION", "พักร้อน"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="leaverequest",
            name="reason",
            field=models.TextField(default="-"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="leaverequest",
            name="start_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="leaverequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "รออนุมัติ"),
                    ("APPROVED", "อนุมัติแล้ว"),
                    ("REJECTED", "ไม่อนุมัติ"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="attendance",
            unique_together={("employee", "date")},
        ),
    ]
