# Generated by Django 5.1.3 on 2025-12-24 18:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "employees",
            "0008_remove_employee_birth_date_remove_employee_emp_id_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="level_weight",
        ),
        migrations.AddField(
            model_name="employee",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="employee",
            name="joined_date",
            field=models.DateField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="วันที่เริ่มงาน",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="employee",
            name="phone_number",
            field=models.CharField(
                blank=True, max_length=15, null=True, verbose_name="เบอร์โทร"
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="leaverequest",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="attendance",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendances",
                to="employees.employee",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="base_allowance",
            field=models.DecimalField(
                decimal_places=2, default=15000, max_digits=10, verbose_name="เงินเดือน"
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="bonus_amount",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="โบนัสสะสม"
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="department",
            field=models.CharField(
                default="General", max_length=100, verbose_name="แผนก"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="employee",
            name="employee_id",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                unique=True,
                verbose_name="รหัสพนักงาน",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="name",
            field=models.CharField(max_length=100, verbose_name="ชื่อ-นามสกุล"),
        ),
        migrations.AlterField(
            model_name="employee",
            name="position",
            field=models.CharField(max_length=100, verbose_name="ตำแหน่ง"),
        ),
        migrations.AlterField(
            model_name="employee",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "ทำงานอยู่"),
                    ("PROBATION", "ทดลองงาน"),
                    ("RESIGNED", "ลาออก"),
                ],
                default="ACTIVE",
                max_length=20,
                verbose_name="สถานะ",
            ),
        ),
        migrations.AlterField(
            model_name="leaverequest",
            name="reason",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="leaverequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "รออนุมัติ"),
                    ("APPROVED", "อนุมัติ"),
                    ("REJECTED", "ไม่อนุมัติ"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
