# Generated by Django 5.2.9 on 2025-12-25 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0009_remove_employee_level_weight_employee_created_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="name",
        ),
        migrations.AddField(
            model_name="employee",
            name="first_name",
            field=models.CharField(default="", max_length=100, verbose_name="ชื่อจริง"),
        ),
        migrations.AddField(
            model_name="employee",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="employee_images/",
                verbose_name="รูปโปรไฟล์",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="last_name",
            field=models.CharField(default="", max_length=100, verbose_name="นามสกุล"),
        ),
    ]
