# Generated by Django 5.2.9 on 2025-12-28 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0010_remove_employee_name_employee_first_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="line_user_id",
            field=models.CharField(
                blank=True,
                help_text="ใส่ User ID ของ LINE (U...) เพื่อรับแจ้งเตือน",
                max_length=50,
                null=True,
            ),
        ),
    ]
